# Generated by Django 4.0.2 on 2022-02-22 13:40

import applications.account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', applications.account.models.UserManager()),
            ],
        ),
    ]
